# Generated by Django 5.0.7 on 2024-07-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppBanco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=11)),
                ('atendente', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=50)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(max_length=50)),
                ('localidade', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('numero', models.CharField(max_length=10)),
                ('datacadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
