# Generated by Django 5.0.7 on 2024-07-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appbanco',
            name='celular',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='appbanco',
            name='cep',
            field=models.CharField(max_length=9),
        ),
    ]
