# Generated by Django 5.0.7 on 2024-07-17 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_appbanco_celular_alter_appbanco_cep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appbanco',
            old_name='atendente',
            new_name='endereco',
        ),
        migrations.RemoveField(
            model_name='appbanco',
            name='logradouro',
        ),
    ]
