# Generated by Django 5.0.7 on 2024-07-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_atendente_appbanco_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appbanco',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='appbanco',
            name='endereco',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appbanco',
            name='localidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appbanco',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='appbanco',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
