# Generated by Django 5.0.7 on 2024-07-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_appbanco_cep_alter_appbanco_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appbanco',
            name='concorda_whatsapp',
            field=models.BooleanField(default=False),
        ),
    ]
