# Generated by Django 5.0.7 on 2024-08-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_appbanco_concorda_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='appbanco',
            name='lideranca',
            field=models.CharField(default='lider', max_length=50),
            preserve_default=False,
        ),
    ]
