# Generated by Django 5.0.7 on 2024-09-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_appbanco_lideranca'),
    ]

    operations = [
        migrations.AddField(
            model_name='appbanco',
            name='datanascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
