# Generated by Django 5.0.7 on 2024-09-04 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_appbanco_datanascimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appbanco',
            old_name='datanascimento',
            new_name='data_nascimento',
        ),
    ]
